### Enoncé

Créer une class StandardScaler2 avec comme méthode fit, transform, fit_transform et en attribut un dicitonnaire params_ qui contient la moyenne et l'écart_type de vos données. Les données en entrées sont uniquement de array numpy (pas des dataframes)
me dire que vous avez terminé avant de faire le bonus. 

En bonus :
- mettre une erreur si on essaye de transform sans avoir de fit
- permettre au code de fonctionner, peut importe si l'entrée est une numpy array ou une dataframe

### Sources

https://towardsdatascience.com/how-to-create-numpy-arrays-from-scratch-3e0341f9ffea

https://kenzotakahashi.github.io/scikit-learns-useful-tools-from-scratch.html

In [37]:
import numpy as np
import pandas as pd

In [38]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [39]:
X = np.array([[ 23., -11.,  47.],
              [ 61.,  89.,  -31.],
              [ 24.,  144., -101.]])

In [40]:
def scale(X):
    new = X - np.mean(X, axis=0)
    return new / np.std(new, axis=0)

In [41]:
np.mean(X, axis=0)

array([ 36.        ,  74.        , -28.33333333])

In [42]:
np.std(X, axis=0)

array([17.68238295, 64.16125518, 60.45016313])

In [43]:
scale(X)

array([[-0.73519503, -1.32478705,  1.24620563],
       [ 1.41383659,  0.23378595, -0.04411347],
       [-0.67864156,  1.0910011 , -1.20209215]])

In [44]:
X

array([[  23.,  -11.,   47.],
       [  61.,   89.,  -31.],
       [  24.,  144., -101.]])

In [45]:
def test(X):
    new = X - np.mean(X, axis=None)
    return new
test

<function __main__.test(X)>

In [46]:
# Moyenne sur colonne de l'array
np.mean(X, axis=0)

array([ 36.        ,  74.        , -28.33333333])

In [47]:
# Moyenne sur ligne de l'array
np.mean(X, axis=1)

array([19.66666667, 39.66666667, 22.33333333])

In [48]:
test(X)

array([[  -4.22222222,  -38.22222222,   19.77777778],
       [  33.77777778,   61.77777778,  -58.22222222],
       [  -3.22222222,  116.77777778, -128.22222222]])

In [49]:
print(scale(X))

[[-0.73519503 -1.32478705  1.24620563]
 [ 1.41383659  0.23378595 -0.04411347]
 [-0.67864156  1.0910011  -1.20209215]]


In practice, you want to use the mean and standard deviation on a training set to a test set. Scikit-learn has StandardScaler class for that.

**fit method** : saves the mean and standard deviation for later use

**transform** : is applied on the same data used to fit, it's essentially doing the same thing as the scale function above

**fit_transform** : is just a shortcut method

In [50]:
import numpy as np
class StandardScaler(object):
    def __init__(self, X):
        pass
    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.scale_ = np.std(X - self.mean_, axis=0)
        return self
    
    def transform(self, X):
        return (X - self.mean_) / self.scale_
    
    def fit_transform(self, X):
        return self.fit(X).transform(X)

In [51]:
print(StandardScaler(X))

In [ ]:
class StandardScaler(object):
    def __init__(self, X):
        pass
    def fit(self, X):
        self.param_= {'mean':0, 'standard':0 }
        self.param_['mean'] = np.mean(X)
        self.param_['standard']= np.std(X - self.param_['mean'])